name = "MangoEnergyEnvironments"
uuid = "648f5313-62c6-43ee-8010-c7c816bb980d"
version = "0.1.0"
authors = ["Rico Schrage"]
repo = "https://github.com/Digitalized-Energy-Systems/MangoEnergyEnvironments.jl"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DistributedResourceOptimization = "bad89516-e02f-43f9-a1d3-8f2ce98dd1a2"
InfrastructureSystems = "2cd47ed4-ca9b-11e9-27f2-ab636a7671f1"
Mango = "5e49fdec-d473-4d14-b295-7bff2fcf1925"
PowerSimulations = "e690365d-45e2-57bb-ac84-44ba829e73c4"
PowerSystemCaseBuilder = "f00506e0-b84f-492a-93c2-c0a9afc4364e"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
InfrastructureSystems = "2.6.0"
Mango = "^0.5"
PowerSimulations = "0.30.2"
PowerSystemCaseBuilder = "1.3.11"
PowerSystems = "4.6.2"
PyCall = "1.96.4"
Revise = "3.6.4"
julia = "^1.9"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
